### ISSUE TITLE
Raw input

### ISSUE THREAD

**Issue by spctr01** [LionSec/xerosploit#146]
When I run xerosplot it shoes error raw input not defined

**Comment by baymax1908** [comment]
I have same issue

**Comment by amar3142** [comment]
you are using python3, use only 'python install.py'

**Comment by azamet90** [comment]
> you are using python3, use only 'python install.py'

if i use python i use already python 3 but if i use python2 it is installing but after i run the tool i get this error:
sudo xerosploit


██╗  ██╗███████╗██████╗  ██████╗ ███████╗██████╗ ██╗      ██████╗ ██╗████████╗
╚██╗██╔╝██╔════╝██╔══██╗██╔═══██╗██╔════╝██╔══██╗██║     ██╔═══██╗██║╚══██╔══╝
 ╚███╔╝ █████╗  ██████╔╝██║   ██║███████╗██████╔╝██║     ██║   ██║██║   ██║   
 ██╔██╗ ██╔══╝  ██╔══██╗██║   ██║╚════██║██╔═══╝ ██║     ██║   ██║██║   ██║   
██╔╝ ██╗███████╗██║  ██║╚██████╔╝███████║██║     ███████╗╚██████╔╝██║   ██║   
╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝ ╚═╝   ╚═╝                                                      


[+]═══════════[ Author : @LionSec1 _-\|/-_ Website: www.neodrix.com ]═══════════[+]

                      [ Powered by Bettercap and Nmap ]
 
┌═════════════════════════════════════════════════════════════════════════════┐
█                                                                             █
█                         Your Network Configuration                          █ 
█                                                                             █
└═════════════════════════════════════════════════════════════════════════════┘     
 
╒═══════════════╤═══════════════════╤══════════════╤═════════╤════════════╕
│  IP Address   │    MAC Address    │   Gateway    │  Iface  │  Hostname  │
╞═══════════════╪═══════════════════╪══════════════╪═════════╪════════════╡
├───────────────┼───────────────────┼──────────────┼─────────┼────────────┤
│ 192.168.43.39 │ 0C:DD:24:2A:FF:76 │ 192.168.43.1 │  wlan0  │ localhost  │
╘═══════════════╧═══════════════════╧══════════════╧═════════╧════════════╛

╔═════════════╦════════════════════════════════════════════════════════════════════╗
║             ║ XeroSploit is a penetration testing toolkit whose goal is to       ║
║ Information ║ perform man in the middle attacks for testing purposes.            ║
║             ║ It brings various modules that allow to realise efficient attacks. ║
║             ║ This tool is Powered by Bettercap and Nmap.                        ║
╚═════════════╩════════════════════════════════════════════════════════════════════╝

[+] Please type 'help' to view commands.

Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined

**Comment by Niteshsahni** [comment]
same

**Comment by amar3142** [comment]
in python3 the syntax of 'raw_input' is replaced by 'input' only.. so You can use python2 to run the file or you can edit xerosploit.py file and replace all 'raw_input' to 'input'.

**Comment by pscharan** [comment]
how can i edit the file

**Comment by pscharan** [comment]
its not taking edit.

**Comment by curseblood123** [comment]
![image](https://user-images.githubusercontent.com/81659528/121339789-49e49200-c938-11eb-9ddf-ea094405d1f0.png)

**Comment by curseblood123** [comment]
why i cant edit that

**Comment by americanitunes101** [comment]
> why i cant edit that

Use
`nano xerosploit.py`
not xerosploit nano...

**Comment by ikibilgin** [comment]
Traceback (most recent call last):
  File "xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables
