### ISSUE TITLE
Xerosploit Is not showing Hosts

### ISSUE THREAD

**Issue by ParthJadhav** [LionSec/xerosploit#155]
:::::When I try to scan its given me::::

                                                

[+]═══════════[ Author : @LionSec1 _-\|/-_ Website: lionsec.net ]═══════════[+]

                      [ Powered by Bettercap and Nmap ]
 
┌═════════════════════════════════════════════════════════════════════════════┐
█                                                                             █
█                         Your Network Configuration                          █ 
█                                                                             █
└═════════════════════════════════════════════════════════════════════════════┘     
 
╒═══════════════╤═══════════════════╤═════════════╤═════════╤════════════╕
│  IP Address   │    MAC Address    │   Gateway   │  Iface  │  Hostname  │
╞═══════════════╪═══════════════════╪═════════════╪═════════╪════════════╡
├───────────────┼───────────────────┼─────────────┼─────────┼────────────┤
│ 172.16.13.140 │ xx:xx:xx:xx:xx:xx │ 172.16.13.2 │  eth0   │ kali-linux │
╘═══════════════╧═══════════════════╧═════════════╧═════════╧════════════╛

╔═════════════╦════════════════════════════════════════════════════════════════════╗
║             ║ XeroSploit is a penetration testing toolkit whose goal is to       ║
║ Information ║ perform man in the middle attacks for testing purposes.            ║
║             ║ It brings various modules that allow to realise efficient attacks. ║
║             ║ This tool is Powered by Bettercap and Nmap.                        ║
╚═════════════╩════════════════════════════════════════════════════════════════════╝

[+] Please type 'help' to view commands.

Xero ➮ scan

[++] Mapping your network ... 

[+]═══════════[ Devices found on your network ]═══════════[+]

╔═══════════════╦═══════════════════╦═══════════════╗
║ IP Address    ║ Mac Address       ║ Manufacturer  ║
╠═══════════════╬═══════════════════╬═══════════════╣
║ 172.16.13.1   ║ XXXXXXXXXXXX ║ (VMware)      ║
║ 172.16.13.2   ║ XXXXXXXXXXXX ║ (VMware)      ║
║ 172.16.13.254 ║XXXXXXXXXXXX ║ (VMware)      ║
║ 172.16.13.140 ║ XXXXXXXXXXXXx ║ (This device) ║
║               ║                   ║               ║
╚═══════════════╩═══════════════════╩═══════════════╝

[+] Please choose a target (e.g. 192.168.1.10). Enter 'help' for more information.

Xero ➮

**Comment by sarthak1598** [comment]
check If you have installed all the required  modules it requires to execute the script properly .
if not then install them properly and update your  system .
Then ., try to run the script , because i got the same issue then i did the same , so this same can be the cause of your problem.

**Comment by rocko2020** [comment]
yes same problem man.any solution?

**Comment by omarmerheb** [comment]
xerosploit is very good but ve huge nd oo mny issues and problms e need the author to updte it
