### ISSUE TITLE
Please help...i got this problem

### ISSUE THREAD

**Issue by GetRektBoy724** [LionSec/xerosploit#165]
When i run the xerosploit,i get this
root324@localhost:/opt/xerosploit$ su
root@localhost:/opt/xerosploit# python xerosploit.py
sh: 1: iwgetid: not found

▒██   ██▒▓█████  ██▀███   ▒█████    ██████  ██▓███   ██▓     ▒█████   ██▓▄▄▄█████▓
▒▒ █ █ ▒░▓█   ▀ ▓██ ▒ ██▒▒██▒  ██▒▒██    ▒ ▓██░  ██▒▓██▒    ▒██▒  ██▒▓██▒▓  ██▒ ▓▒
░░  █   ░▒███   ▓██ ░▄█ ▒▒██░  ██▒░ ▓██▄   ▓██░ ██▓▒▒██░    ▒██░  ██▒▒██▒▒ ▓██░ ▒░
 ░ █ █ ▒ ▒▓█  ▄ ▒██▀▀█▄  ▒██   ██░  ▒   ██▒▒██▄█▓▒ ▒▒██░    ▒██   ██░░██░░ ▓██▓ ░
▒██▒ ▒██▒░▒████▒░██▓ ▒██▒░ ████▓▒░▒██████▒▒▒██▒ ░  ░░██████▒░ ████▓▒░░██░  ▒██▒ ░
▒▒ ░ ░▓ ░░░ ▒░ ░░ ▒▓ ░▒▓░░ ▒░▒░▒░ ▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▒░▓  ░░ ▒░▒░▒░ ░▓    ▒ ░░
░░   ░▒ ░ ░ ░  ░  ░▒ ░ ▒░  ░ ▒ ▒░ ░ ░▒  ░ ░░▒ ░     ░ ░ ▒  ░  ░ ▒ ▒░  ▒ ░    ░
 ░    ░     ░     ░░   ░ ░ ░ ░ ▒  ░  ░  ░  ░░         ░ ░   ░ ░ ░ ▒   ▒ ░  ░
 ░    ░     ░  ░   ░         ░ ░        ░               ░  ░    ░ ░   ░

[+]═══════════[ Author : @LionSec1 _-\|/-_ Website: lionsec.net ]═══════════[+]

                      [ Powered by Bettercap and Nmap ]

┌═════════════════════════════════════════════════════════════════════════════┐
█                                                                             █
█                         Your Network Configuration                          █
█                                                                             █
└═════════════════════════════════════════════════════════════════════════════┘

Traceback (most recent call last):
  File "xerosploit.py", line 980, in main
    home()
  File "xerosploit.py", line 89, in home
    print (tabulate(table, stralign="center",tablefmt="fancy_grid",headers="firstrow"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-71: ordinal not in range(128)
root@localhost:/opt/xerosploit#

**Comment by arminh4ck3r** [comment]
enter this code at terminal 
export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin"
