### ISSUE TITLE
Xerosploit does not respond while running most of the modules in Ubuntu VM

### ISSUE THREAD

**Issue by jaredliw** [LionSec/xerosploit#185]
Envirament: Oracle VM Virtualbox Ubuntu
I am trying to run xerosploit on Ubuntu. When i run the module 'sniff' or 'yplay', it hans there for a long time and no respond are being given.

Can anyone help me to solve this? 
Thank you.

**Comment by jaredliw** [comment]
Besides, when i scan the network, it does show my phone and other computers which is connecting to the same network. How can I solve this? Is it because I am running on virtual machine?

**Comment by Mama0africa** [comment]
@jaredliw did you find any clues? i have same issue and cant find answer...

**Comment by baisha6** [comment]
How to solve it
