### ISSUE TITLE
Please help..Getting error.

### ISSUE THREAD

**Issue by mockinjay-dev** [LionSec/xerosploit#220]
Traceback (most recent call last):
  File "xerosploit.py", line 980, in main
    home()
  File "xerosploit.py", line 89, in home
    print (tabulate(table, stralign="center",tablefmt="fancy_grid",headers="firstrow"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-76: ordinal not in range(128)

**Comment by jeyaselvamurugan** [comment]
try with python2

**Comment by umeshgain** [comment]
Update and Upgrade if necessary (upgrade may take a while)
sudo apt-get update
sudo apt-get upgrade

Install dependencies manually first.
**nmap**
sudo apt-get install nmap
**hping3**
sudo apt-get install hping3
**build-essential**
sudo apt-get install build-essential
**ruby-dev**
sudo apt-get install ruby-dev
**libpcap-dev**
sudo apt-get install libpcap-dev
**libgmp3-dev**
sudo apt-get install licgmp3-dev
**bettercap** 
sudo apt-get install bettercap
**python-pip** (This will be needed to install "tabulate" and "terminaltables")
sudo apt-get install python-pip
**tabulate**
sudo pip install tabulate
**terminaltables**
sudo pip install terminaltables

If any installation failed with "apt-get install command" trying installing with "pip install"

**Install xerosploit**
git clone https://github.com/LionSec/xerosploit
**cd into xerosploit folder**
sudo python install.py


**In case of WARNING while running install.py such as:**
**WARNING**:  bin/xettercap is not executable
**WARNING**:  See http://guides.rubygems.org/specification-reference/ for help

**cd into xerosploit folder**
cd xerosploit/tools/bettercap/bin/
or open ternimal at /xerosploit/tools/bettercap/bin/
**run** sudo chmod +x xettercap


Launch xerosploit
sudo xerosploit

If you have install xerosploit before the dependencies and you still see issue , I recommend you run the xerosploit installer again.

**Comment by mockinjay-dev** [comment]
Tnx a lot...
