### ISSUE TITLE
error,executing LANG=en && ifconfig --gateway

### ISSUE THREAD

**Issue by ylot0** [LionSec/xerosploit#23]
system:ubuntu14.04 LTS
sniff    error,executing LANG=en && ifconfig --gateway

**Comment by ylot0** [comment]
找到问题所在了，并不是程序问题，是没有配置好。在安装完成之后，默认网卡是eth0，改为wlan0就OK了。

**Comment by trumanyardley** [comment]
Hello I am currently having the same problem as you did and I was wondering how you were able to fix it. I was able to translate your last comment but you know how online translaters can be.

**Comment by 068089dy** [comment]
怎么改的默认网关啊

**Comment by Lexharden** [comment]
The Iface option is in eth0 or wlan?
