### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by anobux** [LionSec/xerosploit#24]
File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

**Comment by wallyssonlima** [comment]
Try:
sudo pip install terminaltables

**Comment by anobux** [comment]
File "/opt/xerosploit/xerosploit.py", line 26, in
from terminaltables import DoubleTable
ImportError: No module named terminaltables

**Comment by wallyssonlima** [comment]
run the following commands in your terminal:
``` bash
apt-get install pip
sudo pip install 
```
