### ISSUE TITLE
ImportError: No module named tabulate

### ISSUE THREAD

**Issue by Hackgodrs** [LionSec/xerosploit#247]
──(root💀kali)-[~/xerosploit]
└─# xerosploit     
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 27, in <module>
    from tabulate import tabulate
ImportError: No module named tabulate

PS:
pip install tabulate --user
Requirement already satisfied: tabulate in /usr/lib/python3/dist-packages (0.8.7)

**Comment by irhdab** [comment]
i also have the same problem.. did you solved it?
