### ISSUE TITLE
Unable to install it on Kali 2021.2

### ISSUE THREAD

**Issue by sauravkhakurel** [LionSec/xerosploit#251]
Package python-pip is not available, but is referred to by another package.

Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

Requirement already satisfied: terminaltables in /usr/lib/python3/dist-packages (3.1.0)

I have no idea why this is not working need help

**Comment by NoNameInspectah** [comment]
Yup. I got the same on Parrot OS

**Comment by Kedislav** [comment]
Same problem here. Seems the program is made to run regular pip instead of pip3.
If I use `pip3 install terminaltables` it will just output `Requirement already satisfied: terminaltables in /usr/lib/python3/dist-packages (3.1.0)`

I somehow got it to run until the ASCII logo (is it ASCII? dunno, new at this don't @ me) by `sudo apt-get install <name of package>` each package listed, yet once it runs (I run it by using `sudo python3 xerosploit.py`) it just outputs this;

`Traceback (most recent call last):
  File "/home/<myuser>/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/home/<myuser>/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined
`
[...] and it will close itself, returning me to normal terminal input.

Hope it gets fixed soon :) it looked really good. I come from Null Byte's video btw.

**Comment by Kedislav** [comment]
> Package python-pip is not available, but is referred to by another package.
> 
> Traceback (most recent call last):
> File "/opt/xerosploit/xerosploit.py", line 26, in
> from terminaltables import DoubleTable
> ImportError: No module named terminaltables
> 
> Requirement already satisfied: terminaltables in /usr/lib/python3/dist-packages (3.1.0)
> 
> I have no idea why this is not working need help

I semi-fixed your problem by running `pip install terminaltables && pip3 install terminaltables` (you can also run these commands separately if one of them fails). I say "semi-fixed" because even though I did this, and refer to my other comment, I still couldn't get it running. Best of luck and tell me if somehow it suddenly works.

**Comment by NoNameInspectah** [comment]
I got this when i ran the program with python 2 (which will allow you to install it)

When i wrote xerosploit in my terminal i got this message when everything loaded up 

```
[+] Please type 'help' to view commands.

Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 981, in main
    cmd0()
  File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
    cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
NameError: name 'raw_input' is not defined

```

**Comment by NoNameInspectah** [comment]
> > Package python-pip is not available, but is referred to by another package.
> > Traceback (most recent call last):
> > File "/opt/xerosploit/xerosploit.py", line 26, in
> > from terminaltables import DoubleTable
> > ImportError: No module named terminaltables
> > Requirement already satisfied: terminaltables in /usr/lib/python3/dist-packages (3.1.0)
> > I have no idea why this is not working need help
> 
> I semi-fixed your problem by running `pip install terminaltables && pip3 install terminaltables` (you can also run these commands separately if one of them fails). I say "semi-fixed" because even though I did this, and refer to my other comment, I still couldn't get it running. Best of luck and tell me if somehow it suddenly works.

Ran both and said that its already satisfied

**Comment by Piyush916** [comment]
is there any alternative for this tool ?

**Comment by nikoskard** [comment]
> I got this when i ran the program with python 2 (which will allow you to install it)
> 
> When i wrote xerosploit in my terminal i got this message when everything loaded up
> 
> ```
> [+] Please type 'help' to view commands.
> 
> Traceback (most recent call last):
>   File "/opt/xerosploit/xerosploit.py", line 981, in main
>     cmd0()
>   File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
>     cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
> NameError: name 'raw_input' is not defined
> ```
> 
> After that i get to the part where it shows you the personal things (MAC and IP) then the program shuts itself down and bring me back to my terminal.
> 
> I did all three tries with python (python, python2, and python3) for python and python3 i got this
> 
> ```
> ╔═════════════╦════════════════════════════════════════════════════════════════════╗
> ║             ║ XeroSploit is a penetration testing toolkit whose goal is to       ║
> ║ Information ║ perform man in the middle attacks for testing purposes.            ║
> ║             ║ It brings various modules that allow to realise efficient attacks. ║
> ║             ║ This tool is Powered by Bettercap and Nmap.                        ║
> ╚═════════════╩════════════════════════════════════════════════════════════════════╝
> 
> [+] Please type 'help' to view commands.
> 
> Traceback (most recent call last):
>   File "/home/inspectah/xerosploit/xerosploit.py", line 981, in main
>     cmd0()
>   File "/home/inspectah/xerosploit/xerosploit.py", line 866, in cmd0
>     cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
> NameError: name 'raw_input' is not defined
> ┌─[inspectah@parrot]─[~/xerosploit]
> └──╼ $
> ```
> 
> and with python2 i got this..
> 
> ```
> ┌─[inspectah@parrot]─[~/xerosploit]
> └──╼ $sudo python2 xerosploit.py
> Traceback (most recent call last):
>   File "xerosploit.py", line 26, in <module>
>     from terminaltables import DoubleTable
> ImportError: No module named terminaltables
> ┌─[✗]─[inspectah@parrot]─[~/xerosploit]
> └──╼ $
> ```
> 
> Everything is ins

> is there any alternative for this tool ?



> I got this when i ran the program with python 2 (which will allow you to install it)
> 
> When i wrote xerosploit in my terminal i got this message when everything loaded up
> 
> ```
> [+] Please type 'help' to view commands.
> 
> Traceback (most recent call last):
>   File "/opt/xerosploit/xerosploit.py", line 981, in main
>     cmd0()
>   File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
>     cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
> NameError: name 'raw_input' is not defined
> ```
> 
> After that i get to the part where it shows you the personal things (MAC and IP) then the program shuts itself down and bring me back to my terminal.
> 
> I did all three tries with python (python, python2, and python3) for python and python3 i got this
> 
> ```
> ╔═════════════╦════════════════════════════════════════════════════════════════════╗
> ║             ║ XeroSploit is a penetration testing toolkit whose goal is to       ║
> ║ Information ║ perform man in the middle attacks for testing purposes.            ║
> ║             ║ It brings various modules that allow to realise efficient attacks. ║
> ║             ║ This tool is Powered by Bettercap and Nmap.                        ║
> ╚═════════════╩════════════════════════════════════════════════════════════════════╝
> 
> [+] Please type 'help' to view commands.
> 
> Traceback (most recent call last):
>   File "/home/inspectah/xerosploit/xerosploit.py", line 981, in main
>     cmd0()
>   File "/home/inspectah/xerosploit/xerosploit.py", line 866, in cmd0
>     cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ➮ \033[1;m").strip()
> NameError: name 'raw_input' is not defined
> ┌─[inspectah@parrot]─[~/xerosploit]
> └──╼ $
> ```
> 
> and with python2 i got this..
> 
> ```
> ┌─[inspectah@parrot]─[~/xerosploit]
> └──╼ $sudo python2 xerosploit.py
> Traceback (most recent call last):
>   File "xerosploit.py", line 26, in <module>
>     from terminaltables import DoubleTable
> ImportError: No module named terminaltables
> ┌─[✗]─[inspectah@parrot]─[~/xerosploit]
> └──╼ $
> ```
> 
> Everything is installed correctly so idk what to do to troubleshoot this issue.

same here. hope the creator will help us

**Comment by Kedislav** [comment]
@sauravkhakurel @NoNameInspectah @Piyush916 @nikoskard

Ok everyone. I seem to have gotten the code up and running (plus python 3!) but idk about it. I've taken the steps from users @rockchest and @adnan007d and the pull requests they've added, yet the creator (@LionSec) is still at large. They seem to be from spain according to their Twitter acc (@LionSec1 in twitter) so I've sent them a tweet hoping they respond.

Check out the pull requests since the original project seems to be a fair amount of years old already, and there has been little to no update despite issues like this one and so many others popping up. Hope this helps a bit and I'll keep you updated if they answer (well, figure you'll see the update in that case).

In case they don't answer for a while, and depending on the license, I might just contact some of the authors from the pull requests (very brilliant people) and re-post the tool on my github page, with (obviously) due credit.

**Comment by yash200** [comment]
i hope it will help you guys 

- first you have to removed your xerosploit folder 
- and then manually install all the dependence 
- now reinstall it again 
-then you have to change python2 to python3 by using (2to3) tool on install.py
by using this command `sudo 2to3 install.py` 

-it will  start installing the dependencies 

- and then you will see this type to error (`Traceback (most recent call last):
File "/opt/xerosploit/xerosploit.py", line 26, in
from terminaltables import DoubleTable
ImportError: No module named terminaltables`)

- now again you have you to use 2to3 on xerosploit.py 
- AND now you have to type `sudo python3 xerosploit.py`

thank you!

**Comment by sauravkhakurel** [comment]
Until @LionSec looks into it, what other options do we have?

**Comment by NoNameInspectah** [comment]
> Until @LionSec looks into it, what other options do we have?

I found a fix. I posted it in issues tho

**Comment by dsxz19-2** [comment]
Ya same i got "raw_input not defined" error but i fixed it

in the "install.py" file in line 48 or where ever it says:

install = os.system("apt-get update && apt-get install -y nmap hping3 build-essential python-pip ruby-dev git libpcap-dev libgmp3-dev && pip install tabulate terminaltables")

replace python-pip with python3-pip

at the top were you import modules add this "from six.moves import input" without the " "

copy and past the xerosploit.py code into a google docs or somewhere where you can do a mass replace

if you are using google docs press ctrl+h and in the first line type raw_input and in the second line type input

and then click "replace all"

I hope this helps. :)

**Comment by sauravkhakurel** [comment]
> > Until @LionSec looks into it, what other options do we have?
> 
> I found a fix. I posted it in issues tho

Thanks
