### ISSUE TITLE
sh: 1: xettercap: not found

### ISSUE THREAD

**Issue by tidilihatim** [LionSec/xerosploit#26]
hello thx for your great work , can you help me please ?
everytime i try somthing like sniff they give me this msg 'sh: 1: xettercap: not found'
thx.

**Comment by ylot0** [comment]
run the following commands in your terminal:
git clone https://github.com/LionSec/xerosploit
cd xerosploit && sudo python install.py
sudo xerosploit

install the dependencies:
sudo apt install pip
sudo pip install tabulate
sudo pip install terminaltables

**Comment by tidilihatim** [comment]
Thx for your reply , i do everything you said but still the same error :/

**Comment by tidilihatim** [comment]
after i do what you said , i remove xerosploit and i install it again and it's work ! thank you.

**Comment by ROhanpersonalkali** [comment]
thanks for the help but i can't install tabulate and terminaltables i use this command to install 
**apt-get install tabulate** 
and it says **E: Unable to locate package tabulate**

**apt-get install terminaltables** 
and it says **E: Unable to locate package terminaltables**

**Comment by NielsNijhof** [comment]
@ROhanpersonalkali they can be installed via pip or easy_install, they're python modules

**Comment by unknownbatman** [comment]
i cant install libcap-dev and libmp3-dev

**Comment by godlike24** [comment]
hey can anyone resolve this??
In xerosploit ping module it show 100% loss how to resolve this .

**Comment by kaiserx101** [comment]
For the new people trying to install xerosploit (just like me) for personal experience.
  I would recomen to Install Dependencies in the first place , even if it is said that dependencies are install automatically.

 Check the repository and add if necessary .
echo "deb http://http.kali.org/kali kali-rolling main contrib non-free" > /etc/apt/sources.list

Update and Upgrade if necessary (upgrade may take a while)
sudo apt-get update
sudo apt-get upgrade

Install dependencies manually first.
**nmap**
          sudo apt-get install nmap
**hping3**
          sudo apt-get install hping3
**build-essential**
          sudo apt-get install build-essential
**ruby-dev**
          sudo apt-get install ruby-dev
**libpcap-dev**
          sudo apt-get install libpcap-dev
**libgmp3-dev**
          sudo apt-get install licgmp3-dev
**bettercap**       <-- better option for xettercap
          sudo apt-get install bettercap
**python-pip** (This will be needed to install "tabulate" and "terminaltables")
         sudo apt-get install python-pip
                **tabulate**
                               sudo pip install tabulate
                **terminaltables**
                               sudo pip install terminaltables

If any installation failed with "apt-get install command" trying installing with "pip install" 

Install xerosploit
 git clone https://github.com/LionSec/xerosploit
 cd into xerosploit folder 
 sudo python install.py

Launch xerosploit
sudo xerosploit 
 if issue launching xerosploit, navigate to xerosploit folder and execute the following
sudo ./xerosploit.py  OR sudo python xerosploit.py

If you have install xerosploit before the dependencies and you still see issue , I recommend you run the xerosploit installer again.
