### ISSUE TITLE
when i type this command:python3 install.py it show me this and i still don't know why

### ISSUE THREAD

**Issue by BaxJimmy** [LionSec/xerosploit#288]
Traceback (most recent call last):
  File "/root/xerosploit/install.py", line 65, in <module>
    main()
  File "/root/xerosploit/install.py", line 45, in main
    system0 = raw_input(">>> ")
NameError: name 'raw_input' is not defined

**Comment by morganliup** [comment]
try to use "python install.py" or "python2 install.py"
not python3

**Comment by DarkcoderSe** [comment]
You can use python3 without installing. Just open the xerosploit.py in editor and replace "input" with "raw_input".  
That's it!

**Comment by ChillVibesMushroom** [comment]
> You can use python3 without installing. Just open the xerosploit.py in editor and replace "input" with "raw_input". That's it!

O I see but due wat about dependency installation I'm just skim reading rn tbh looking for efficient  tools and I found Xerosploit.
