### ISSUE TITLE
cannot load such file -- webrick (LoadError)

### ISSUE THREAD

**Issue by CLAYJFR05** [LionSec/xerosploit#294]
I can't use move module and I'm getting this error.

<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick (LoadError)
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:37:in `<top (required)>'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>'
        from /usr/local/bin/xettercap:25:in `load'
        from /usr/local/bin/xettercap:25:in `<main>'

**Comment by vladimirKing** [comment]
Same issue here.

**Comment by Leo-Aqua** [comment]
same using kali

**Comment by hariyebk** [comment]
I am encountering the same issue

**Comment by hariyebk** [comment]
> I can't use move module and I'm getting this error.
> 
> internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- webrick (LoadError) from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require' from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:37:in `<top (required)>' from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require' from internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require' from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>' from /usr/local/bin/xettercap:25:in `load' from /usr/local/bin/xettercap:25:in `
> '

did you solved it ?

**Comment by AHmedM0stafa** [comment]
Me too !
I trying to use it also and this is what i get Out and not work >>>>
==============================================
Xero»modules ➮ move
 
┌══════════════════════════════════════════════════════════════┐
█                                                              █
█                           Shakescreen                        █
█                                                              █
█                   Shaking Web Browser content                █
└══════════════════════════════════════════════════════════════┘     

[+] Enter 'run' to execute the 'move' command.

Xero»modules»shakescreen ➮ run

[++] Injecting shakescreen.js  ... 

[++] Press 'Ctrl + C' to stop . 



/var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:51:in `rescue in <top (required)>': undefined local variable or method `original_argv' for main:Object (NameError)
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:32:in `<top (required)>'
	from /usr/local/bin/xettercap:25:in `load'
	from /usr/local/bin/xettercap:25:in `<main>'
/usr/lib/ruby/3.0.0/set/sorted_set.rb:4:in `rescue in <top (required)>': The `SortedSet` class has been extracted from the `set` library.You must use the `sorted_set` gem or other alternatives. (RuntimeError)
	from /usr/lib/ruby/3.0.0/set/sorted_set.rb:1:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `const_get'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `block in each_module'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each_module'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:71:in `register_options'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:53:in `load'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/proxy_options.rb:164:in `block in parse!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1618:in `block in parse_in_order'
	from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `catch'
	from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `parse_in_order'
	from /usr/lib/ruby/3.0.0/optparse.rb:1595:in `order!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1701:in `permute!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1726:in `parse!'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/options.rb:54:in `parse!'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
	from /usr/local/bin/xettercap:25:in `load'
	from /usr/local/bin/xettercap:25:in `<main>'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- sorted_set (LoadError)
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/lib/ruby/3.0.0/set/sorted_set.rb:2:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `const_get'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `block in each_module'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each_module'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:71:in `register_options'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:53:in `load'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/proxy_options.rb:164:in `block in parse!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1618:in `block in parse_in_order'
	from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `catch'
	from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `parse_in_order'
	from /usr/lib/ruby/3.0.0/optparse.rb:1595:in `order!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1701:in `permute!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1726:in `parse!'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/options.rb:54:in `parse!'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
	from /usr/local/bin/xettercap:25:in `load'
	from /usr/local/bin/xettercap:25:in `<main>'

[+] Enter 'run' to execute the 'move' command.

=================================================


any one can help to solve this error !!!

**Comment by CLAYJFR05** [comment]
I didn't figure out how to fix this issue and seems like the only possible way to fix this problem is install xerosploit in fresh kali linux.

**Comment by xenoveon** [comment]
[MrDrache333](https://github.com/MrDrache333) commented [on Apr 4](https://github.com/LionSec/xerosploit/issues/153#issuecomment-1087347884)
Had the Same issue.
This is because xettercap uses a Library called set and not the Library sorted_set.

To fix this issue you could simply install the needed library with sudo gem install sorted_set

**Comment by FLOW-AW** [comment]
same





var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:51:in `rescue in <top (required)>': undefined local variable or method `original_argv' for main:Object (NameError)
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:32:in `<top (required)>'
	from /usr/local/bin/xettercap:25:in `load'
	from /usr/local/bin/xettercap:25:in `<main>'
/usr/lib/ruby/3.0.0/set/sorted_set.rb:4:in `rescue in <top (required)>': The `SortedSet` class has been extracted from the `set` library.You must use the `sorted_set` gem or other alternatives. (RuntimeError)
	from /usr/lib/ruby/3.0.0/set/sorted_set.rb:1:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `const_get'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `block in each_module'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each_module'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:71:in `register_options'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:53:in `load'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/proxy_options.rb:164:in `block in parse!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1618:in `block in parse_in_order'
	from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `catch'
	from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `parse_in_order'
	from /usr/lib/ruby/3.0.0/optparse.rb:1595:in `order!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1701:in `permute!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1726:in `parse!'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/options.rb:54:in `parse!'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
	from /usr/local/bin/xettercap:25:in `load'
	from /usr/local/bin/xettercap:25:in `<main>'
<internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- sorted_set (LoadError)
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /usr/lib/ruby/3.0.0/set/sorted_set.rb:2:in `<top (required)>'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `const_get'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:93:in `block in each_module'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:92:in `each_module'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:71:in `register_options'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/proxy/http/module.rb:53:in `load'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/proxy_options.rb:164:in `block in parse!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1618:in `block in parse_in_order'
	from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `catch'
	from /usr/lib/ruby/3.0.0/optparse.rb:1601:in `parse_in_order'
	from /usr/lib/ruby/3.0.0/optparse.rb:1595:in `order!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1701:in `permute!'
	from /usr/lib/ruby/3.0.0/optparse.rb:1726:in `parse!'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap/options/options.rb:54:in `parse!'
	from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:24:in `<top (required)>'
	from /usr/local/bin/xettercap:25:in `load'
	from /usr/local/bin/xettercap:25:in `<main>'

**Comment by UtechP-40** [comment]
Traceback (most recent call last):
	2: from /usr/bin/xettercap:16:in `<main>'
	1: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- bettercap (LoadError)

i am getting this error

**Comment by UtechP-40** [comment]
plese help me solve this error
Traceback (most recent call last):
	2: from /usr/bin/xettercap:16:in `<main>'
	1: from /usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require'
/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- bettercap (LoadError)

**Comment by XM1N21KR1** [comment]
> I can't use move module and I'm getting this error.
> 
> internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require': cannot load such file -- webrick (LoadError) from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require' from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/lib/bettercap.rb:37:in `<top (required)>' from <internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb>:85:in `require' from internal:/usr/lib/ruby/vendor_ruby/rubygems/core_ext/kernel_require.rb:85:in `require' from /var/lib/gems/3.0.0/gems/xettercap-1.5.7xerob/bin/xettercap:16:in `<top (required)>' from /usr/local/bin/xettercap:25:in `load' from /usr/local/bin/xettercap:25:in `
> 
> '

same issue here

**Comment by braintxx** [comment]
same  issue.
