### ISSUE TITLE
No module named terminaltables

### ISSUE THREAD

**Issue by NYT777** [LionSec/xerosploit#308]
Xerosploit has been sucessfuly instaled. Execute 'xerosploit' in your terminal.
┌─[root@Paro]─[/lib/xerosploit]
└──╼ #xerosploit
bash: xerosploit: command not found

.

┌─[✗]─[root@Paro]─[/lib/xerosploit]
└──╼ #python ./xerosploit.py
Traceback (most recent call last):
  File "./xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

Help? Im running Parrot OS...

**Comment by kyujin100715** [comment]
pip install terminaltables

**Comment by NYT777** [comment]
┌─[✗]─[root@Paro]─[/home/***/...
└──╼ #pip install terminaltables
Requirement already satisfied: terminaltables in /usr/local/lib/python3.9/dist-packages (3.1.10)

┌─[root@Paro]─[/home/***/...
└──╼ #python xerosploit.py
Traceback (most recent call last):
  File "xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable
ImportError: No module named terminaltables

it did not solve the problem

**Comment by arazmoazzemi** [comment]
You should be use python 2.7 version

**Comment by NYT777** [comment]
@arazmoazzemi same thing

Traceback (most recent call last):
  File "./xerosploit.py", line 28, in <module>
    from terminaltables.other_tables import DoubleTable
ImportError: No module named terminaltables.other_tables
