### ISSUE TITLE
NameError: name 'raw_input' is not defined

### ISSUE THREAD

**Issue by berezenko04** [LionSec/xerosploit#324]
Traceback (most recent call last):
    File "/opt/xerosploit/xerosploit.py", line 981, in main
         cmd0()
    File "/opt/xerosploit/xerosploit.py", line 866, in cmd0
         cmd_0 = raw_input("\033[1;36m\033[4mXero\033[0m\033[1;36m ==> \033[1;m").strip()
NameError: name 'raw_input' is not defined

**Comment by rawss02** [comment]
Change raw_input(>>>>>) to input(>>>>>)

**Comment by fernandofatech** [comment]
Woks, thanks

**Comment by tinihazuni** [comment]
i do not understand what to do

**Comment by rawss02** [comment]
I'll upload the fixed code later today, or I'll email it to you.
Keep communicating if you experience any further issues.

**Comment by Keterix** [comment]
> i do not understand what to do

Just go to xerosploit folder and look for the install.py, open it and search for raw_input, you can search on the file by just clicking on the top bar the search button, and just write raw, then delete the "raw_" and just keep the input.
