### ISSUE TITLE
I have a problem, but I don't know why :(

### ISSUE THREAD

**Issue by Saolart** [LionSec/xerosploit#46]
root@kali:~# cd xerosploit/ && python install.py
 
┌══════════════════════════════════════════════════════════════┐
█                                                              █
█                     Xerosploit Installer                     █
█                                                              █
└══════════════════════════════════════════════════════════════┘     

[++] Please choose your operating system.

1) Ubuntu / Kali linux / Others
2) Parrot OS

>>> 1

[++] Installing Xerosploit ... 
Hit:1 http://old.kali.org/kali sana InRelease            
Чтение списков пакетов… Готово                           
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
build-essential is already the newest version (11.7).
hping3 is already the newest version (3.a2.ds2-7).
libgmp3-dev is already the newest version (2:6.0.0+dfsg-6).
libpcap-dev is already the newest version (1.6.2-2).
ruby-dev is already the newest version (1:2.1.5+deb8u1).
nmap is already the newest version (7.01-1).
python-pip is already the newest version (1.5.6-7).
git is already the newest version (1:2.7.0~rc3-1).
Следующие пакеты устанавливались автоматически и больше не требуются:
  libjs-jquery-easing libjs-jquery-fancybox libjs-jquery-mousewheel libuv1
  nodejs ruby-ansi ruby-daemons ruby-dataobjects ruby-dataobjects-mysql
  ruby-dataobjects-postgres ruby-dataobjects-sqlite3 ruby-diff-lcs
  ruby-dm-core ruby-dm-do-adapter ruby-dm-migrations ruby-dm-serializer
  ruby-dm-sqlite-adapter ruby-docile ruby-em-websocket ruby-erubis
  ruby-eventmachine ruby-execjs ruby-geoip ruby-librex ruby-libv8
  ruby-mojo-magick ruby-msfrpc-client ruby-msgpack ruby-parseconfig ruby-qr4r
  ruby-rack ruby-rack-protection ruby-rainbow ruby-ref ruby-rexec ruby-rqrcode
  ruby-rspec-expectations ruby-rspec-support ruby-rubydns ruby-simplecov
  ruby-simplecov-html ruby-sinatra ruby-term-ansicolor ruby-therubyracer
  ruby-tilt ruby-tins ruby-uglifier thin
Для их удаления используйте «apt autoremove».
обновлено 0, установлено 0 новых пакетов, для удаления отмечено 0 пакетов, и 9 пакетов не обновлено.
Requirement already satisfied (use --upgrade to upgrade): tabulate in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied (use --upgrade to upgrade): terminaltables in /usr/local/lib/python2.7/dist-packages
Cleaning up...
WARNING:  bin/xettercap is not executable
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: xettercap
  Version: 1.5.7xerob
  File: xettercap-1.5.7xerob.gem
Fetching: colorize-0.8.1.gem (100%)
Successfully installed colorize-0.8.1
Fetching: pcaprub-0.12.4.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing xettercap-1.5.7xerob.gem:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby2.2 -r ./siteconf20161218-14199-ex3174.rb extconf.rb
mkmf.rb can't find header files for ruby at /usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.2.0/gems/pcaprub-0.12.4 for inspection.
Results logged to /var/lib/gems/2.2.0/extensions/x86_64-linux/2.2.0/pcaprub-0.12.4/gem_make.out
Xerosploit has been sucessfuly instaled. Execute 'xerosploit' in your terminal.

**Comment by Saolart** [comment]
root@kali:~/xerosploit# xerosploit
bash: xerosploit: command not found

**Comment by zayaslui** [comment]
bash: xerosploit: command not found

**Comment by Descilian** [comment]
same problem any help ?
