### ISSUE TITLE
Invalid parser name 'CREDITCARD'

### ISSUE THREAD

**Issue by ekkimosi** [LionSec/xerosploit#47]
Hi, when I start sniff module and activating sslstrip, xerosploit give me error [E] Invalid parser name 'CREDITCARD'.

**Comment by alejandrombc** [comment]
same

**Comment by fra71195** [comment]
same, some solution?

**Comment by salemalkhabuli** [comment]
salam  
pleas
I have  problem       bash: xerosploit: command not found

**Comment by salemalkhabuli** [comment]
I have problem      bash: xerosploit: command not found
