### ISSUE TITLE
unable to launch tool

### ISSUE THREAD

**Issue by astr0b0t** [LionSec/xerosploit#63]
I have installed xerosploit in parrot os it was installed sucessfully but after installing when ever I am trying to launch the tool this error is coming:
$xerosploit
Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 26, in <module>
    from terminaltables import DoubleTable

**Comment by ulysse07** [comment]
Same problem...

**Comment by astr0b0t** [comment]
found a solution :
sudo pip install terminaltables
sudo pip install tabulate
