### ISSUE TITLE
Error Launching

### ISSUE THREAD

**Issue by Veroxidium** [LionSec/xerosploit#78]
This issue could be a few things, I just installed kali full distribution and fully upgraded, and updated, ruby libsec and my gem is all updated, i have also  played around with bettercap so I have installed bettercap and upgraded it as well, I have installed figlet and added a custom header to my terminal this might be related i dont know, I installed xerosploit with zero issues but upon launching via root console on kali linux such as root@kali:~# xerosploit I have then been reached with this error. root@kali:~# xerosploit

▒██   ██▒▓█████  ██▀███   ▒█████    ██████  ██▓███   ██▓     ▒█████   ██▓▄▄▄█████▓
▒▒ █ █ ▒░▓█   ▀ ▓██ ▒ ██▒▒██▒  ██▒▒██    ▒ ▓██░  ██▒▓██▒    ▒██▒  ██▒▓██▒▓  ██▒ ▓▒
░░  █   ░▒███   ▓██ ░▄█ ▒▒██░  ██▒░ ▓██▄   ▓██░ ██▓▒▒██░    ▒██░  ██▒▒██▒▒ ▓██░ ▒░
 ░ █ █ ▒ ▒▓█  ▄ ▒██▀▀█▄  ▒██   ██░  ▒   ██▒▒██▄█▓▒ ▒▒██░    ▒██   ██░░██░░ ▓██▓ ░
▒██▒ ▒██▒░▒████▒░██▓ ▒██▒░ ████▓▒░▒██████▒▒▒██▒ ░  ░░██████▒░ ████▓▒░░██░  ▒██▒ ░
▒▒ ░ ░▓ ░░░ ▒░ ░░ ▒▓ ░▒▓░░ ▒░▒░▒░ ▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▒░▓  ░░ ▒░▒░▒░ ░▓    ▒ ░░ 
░░   ░▒ ░ ░ ░  ░  ░▒ ░ ▒░  ░ ▒ ▒░ ░ ░▒  ░ ░░▒ ░     ░ ░ ▒  ░  ░ ▒ ▒░  ▒ ░    ░  
 ░    ░     ░     ░░   ░ ░ ░ ░ ▒  ░  ░  ░  ░░         ░ ░   ░ ░ ░ ▒   ▒ ░  ░    
 ░    ░     ░  ░   ░         ░ ░        ░               ░  ░    ░ ░   ░         

[+]═══════════[ Author : @LionSec1 _-\|/-_ Website: lionsec.net ]═══════════[+]

                      [ Powered by Bettercap and Nmap ]

┌═════════════════════════════════════════════════════════════════════════════┐
█                                                                             █
█                         Your Network Configuration                          █
█                                                                             █
└═════════════════════════════════════════════════════════════════════════════┘ 

Traceback (most recent call last):
  File "/opt/xerosploit/xerosploit.py", line 980, in main
    home()
  File "/opt/xerosploit/xerosploit.py", line 89, in home
    print (tabulate(table, stralign="center",tablefmt="fancy_grid",headers="firstrow"))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-111: ordinal not in range(128)
root@kali:~#

i really don't know what to do

**Comment by rootkaali** [comment]
guys answer to this error>

**Comment by pfftdammitchris** [comment]
Read the fix at: #88
