### ISSUE TITLE
Ubuntu 17.04

### ISSUE THREAD

**Issue by DENYHAX** [LionSec/xerosploit#90]
![screenshot from 2017-09-03 01-17-45](https://user-images.githubusercontent.com/22339147/29999376-fba07980-9045-11e7-8c57-62b5d65a17d7.png)
Just installed it.
Any idea?

**Comment by usama7628674** [comment]
Just use the following commands
`pip install setuptools`
`pip install terminaltables`
and after that reinstall xerosploit and run it and report back

**Comment by DENYHAX** [comment]
Thanks for your help! Now its working perfectly. :)
